name: local_development CI

on:
  workflow_dispatch:
  push:
    paths:
      - "containerized_leaf/local_development/**"
      - ".github/workflows/ci.yml"

jobs:
  local_dev:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Docker info
        run: docker info

      - name: Prepare Leaf
        run: |
          cd local_development
          chmod +x prepare_compose.sh
          ./prepare_compose.sh

      - name: Build & start Leaf
        run: |
          cd local_development
          docker compose up -d --build

      - name: Show status
        run: |
          cd local_development
          docker compose ps
          docker compose logs --tail=200

      - name: Tear down
        if: always()
        run: |
          cd local_development
          docker compose down -v