name: local_development CI

on:
  workflow_dispatch:
  push:
    paths:
      - "containerized_leaf/local_development/**"
      - ".github/workflows/ci.yml"

jobs:
  local_dev:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v5

      - name: Docker info
        run: docker info

      - name: Fix Preparation Script Permissions
        working-directory: containerized_leaf/local_development
        run: chmod +x prepare_compose.sh


      - name: Run Preparation Script 
        working-directory: containerized_leaf/local_development
        run: ./prepare_compose.sh

      - name: Docker Compose Build & start Leaf
        working-directory: containerized_leaf/local_development
        run: docker compose up -d --build

      - name: Show status
        working-directory: containerized_leaf/local_development
        run: |
          docker compose ps
          docker compose logs --tail=200

